const constant = {
  // baseURL: "http://360cubes.com/pet_birthday_staging/public/api/",
  baseURL: "http://192.34.60.217/php72/pet_birthday_web_api/public/api/",
  userLogin: "user/login",
  getUser: "user/profile",
  socialLogin: "user/social",
  userSignup: "user/signup",
  forgotPassword: "user/forgot/password",
  changePassword: "user/change/password",
  add: "user/post/create",
  editOwerOrPet: "user/post/update",
  deleteOwnerOrPet: "user/post/delete",
  petType: "user/posttype",
  petSize: "user/postsize",
  getOwnerOrPet: "user/post/list",
  search: "user/post/search",
  updateUser: 'user/profile/update',
  getPhotos: "user/album/list",
  uploadPhoto: "user/album/create",
  getPetBday: "user/bdayage/search",
  deletePhoto: "user/album/delete",
  getParties: "user/event/list",
  createEvent: "user/event/create",
  deleteParty: "user/event/delete",
  updateParty: "user/event/update",
  sameBirthday: "user/samebirthday/search",
  sameAge: "user/sameageday/search",
  contactUs: "user/contact",
  famousBirthday: "user/famousebday/search",
  getMontage: "user/montage",
  addMontage: "user/montage/create",
  deleteMontage: "user/montage/delete",
  getTribute: "user/tribute",
  addTribute: "user/tribute/create",
  deleteTribute: "user/tribute/delete",
  enableDisableTribute: "user/tribute/active",
  payment: "user/payment",
  getMontageMusic: "user/music/list",
  getPlans: "user/subscription/plans",
  addCard: "user/subscription/addcard",
  getCards: "user/subscription/cardlist",
  setDefaultCard: "user/subscription/adddefaultcard",
  getInvoice: "user/subscription/invoicelist",
  cancelSubscription: "user/subscription/cancelsubscription"
}

export default constant;