import translate, { getCurrentLocale } from '../Modules/Localization/i18n';

export const updateAppConstants = () => {
  AppConstants = {
    customer: translate("customer"),
    worker: translate("worker"),
    pleaseSignInToContinue: translate("pleaseSignInToContinue"),
    signIn: translate("signIn"),
    forgot: translate("forgot"),
    name: translate("name"),
    phone: translate("phone"),
    or: translate("or"),
    loginWithSocialMedia: translate("loginWithSocialMedia"),
    dontHaveAnAccount: translate("dontHaveAnAccount"),
    username: translate("username"),
    email: translate("email"),
    password: translate("password"),
    phoneNumber: translate("phoneNumber"),
    confirmPassword: translate("confirmPassword"),
    signUp: translate("signUp"),
    alreadyHaveAnAccount: translate("alreadyHaveAnAccount"),
    myJobs: translate("myJobs"),
    requests: translate("requests"),
    todo: translate("todo"),
    onGoing: translate("onGoing"),
    done: translate("done"),
    componayProfile: translate("componayProfile"),
    notifications: translate("notifications"),
    settings: translate("settings"),
    logout: translate("logout"),
    accept: translate("accept"),
    reject: translate("reject"),
    startService: translate("startService"),
    details: translate("details"),
    book: translate("book"),
    nearBy: translate("nearBy"),
    specialOffers: translate("specialOffers"),
    allServiceProvides: translate("allServiceProvides"),
    about: translate("about"),
    services: translate("services"),
    address: translate("address"),
    workingHours: translate("workingHours"),
    packages: translate("packages"),
    package: translate("package"),
    schedule: translate("schedule"),
    chooseDate: translate("chooseDate"),
    chooseTime: translate("chooseTime"),
    discountCode: translate("discountCode"),
    scheduleNow: translate("scheduleNow"),
    home: translate("home"),
    myBookings: translate("myBookings"),
    rateApplication: translate("rateApplication"),
    inviteFriends: translate("inviteFriends"),
    profile: translate("profile"),
    serviceDetails: translate("serviceDetails"),
    editProfile: translate("editProfile"),
    alert: translate("alert"),
    ok: translate("ok"),
    alertEmail: translate("alertEmail"),
    alertPassword: translate("alertPassword"),
    alertUsername: translate("alertUsername"),
    alertConfirmPassword: translate("alertConfirmPassword"),
    alertPasswordNotMatch: translate("alertPasswordNotMatch"),
    alertCurrentPassword: translate("alertCurrentPassword"),
    alertPhoneNo: translate("alertPhoneNo"),
    alertNewPassword: translate("alertNewPassword"),
    submit: translate("submit"),
    changePassword: translate("changePassword"),
    aboutUs: translate("aboutUs"),
    privacyPolicy: translate("privacyPolicy"),
    termsAndCondition: translate("termsAndCondition"),
    currentPassword: translate("currentPassword"),
    newPassword: translate("newPassword"),
    alertNewPasswordNotMatch: translate("alertNewPasswordNotMatch"),
    scheduled: translate("scheduled"),
    completed: translate("completed"),
    confirm: translate("confirm"),
    id: translate("id"),
    save: translate("save"),
    alertChooseDate: translate("alertChooseDate"),
    alertChooseTime: translate("alertChooseTime"),
    alertWrongDate: translate("alertWrongDate"),
    alertWrongTime: translate("alertWrongTime"),
    search: translate("search"),
    map: translate("map"),
    currentLocation: translate("currentLocation"),
    useCurrentLocation: translate("useCurrentLocation"),
    changeLocation: translate("changeLocation"),
    enterLocation: translate("enterLocation"),
    go: translate("go"),
    alertLocationPermissionDenied: translate("alertLocationPermissionDenied"),
    alertLocationPositionUnavailable: translate("alertLocationPositionUnavailable"),
    alertLocationRequestTimeout: translate("alertLocationRequestTimeout"),
    alertSuccessSchedule: translate("alertSuccessSchedule"),
    noServicesFound: translate("noServicesFound"),
    status: translate("status"),
    alertUnknownError: translate("alertUnknownError"),

    //NEW
    language: translate("language"),
    changeLanguageMessage: translate('changeLanguageMessage'),
    tipPopupText: translate('tipPopupText'),
    yes: translate('yes'),
    no: translate('no'),
    chooseLanguage: translate('chooseLanguage'),
    scheduleSummary: translate('scheduleSummary'),
    packageDetails: translate('packageDetails'),
    dateAndTime: translate('dateAndTime'),
    description: translate('description'),
    amount : translate('amount')
  }
}
export let AppConstants;

AppConstants = {
  customer: translate("customer"),
  worker: translate("worker"),
  pleaseSignInToContinue: translate("pleaseSignInToContinue"),
  signIn: translate("signIn"),
  forgot: translate("forgot"),
  name: translate("name"),
  phone: translate("phone"),
  or: translate("or"),
  loginWithSocialMedia: translate("loginWithSocialMedia"),
  dontHaveAnAccount: translate("dontHaveAnAccount"),
  username: translate("username"),
  email: translate("email"),
  password: translate("password"),
  phoneNumber: translate("phoneNumber"),
  confirmPassword: translate("confirmPassword"),
  signUp: translate("signUp"),
  alreadyHaveAnAccount: translate("alreadyHaveAnAccount"),
  myJobs: translate("myJobs"),
  requests: translate("requests"),
  todo: translate("todo"),
  onGoing: translate("onGoing"),
  done: translate("done"),
  componayProfile: translate("componayProfile"),
  notifications: translate("notifications"),
  settings: translate("settings"),
  logout: translate("logout"),
  accept: translate("accept"),
  reject: translate("reject"),
  startService: translate("startService"),
  details: translate("details"),
  book: translate("book"),
  nearBy: translate("nearBy"),
  specialOffers: translate("specialOffers"),
  allServiceProvides: translate("allServiceProvides"),
  about: translate("about"),
  services: translate("services"),
  address: translate("address"),
  workingHours: translate("workingHours"),
  packages: translate("packages"),
  package: translate("package"),
  schedule: translate("schedule"),
  chooseDate: translate("chooseDate"),
  chooseTime: translate("chooseTime"),
  discountCode: translate("discountCode"),
  scheduleNow: translate("scheduleNow"),
  home: translate("home"),
  myBookings: translate("myBookings"),
  rateApplication: translate("rateApplication"),
  inviteFriends: translate("inviteFriends"),
  profile: translate("profile"),
  serviceDetails: translate("serviceDetails"),
  editProfile: translate("editProfile"),
  alert: translate("alert"),
  ok: translate("ok"),
  alertEmail: translate("alertEmail"),
  alertPassword: translate("alertPassword"),
  alertUsername: translate("alertUsername"),
  alertConfirmPassword: translate("alertConfirmPassword"),
  alertPasswordNotMatch: translate("alertPasswordNotMatch"),
  alertCurrentPassword: translate("alertCurrentPassword"),
  alertPhoneNo: translate("alertPhoneNo"),
  alertNewPassword: translate("alertNewPassword"),
  submit: translate("submit"),
  changePassword: translate("changePassword"),
  aboutUs: translate("aboutUs"),
  privacyPolicy: translate("privacyPolicy"),
  termsAndCondition: translate("termsAndCondition"),
  currentPassword: translate("currentPassword"),
  newPassword: translate("newPassword"),
  alertNewPasswordNotMatch: translate("alertNewPasswordNotMatch"),
  scheduled: translate("scheduled"),
  completed: translate("completed"),
  confirm: translate("confirm"),
  id: translate("id"),
  save: translate("save"),
  alertChooseDate: translate("alertChooseDate"),
  alertChooseTime: translate("alertChooseTime"),
  alertWrongDate: translate("alertWrongDate"),
  alertWrongTime: translate("alertWrongTime"),
  search: translate("search"),
  map: translate("map"),
  currentLocation: translate("currentLocation"),
  useCurrentLocation: translate("useCurrentLocation"),
  changeLocation: translate("changeLocation"),
  enterLocation: translate("enterLocation"),
  go: translate("go"),
  alertLocationPermissionDenied: translate("alertLocationPermissionDenied"),
  alertLocationPositionUnavailable: translate("alertLocationPositionUnavailable"),
  alertLocationRequestTimeout: translate("alertLocationRequestTimeout"),
  alertSuccessSchedule: translate("alertSuccessSchedule"),
  noServicesFound: translate("noServicesFound"),
  status: translate("status"),
  alertUnknownError: translate("alertUnknownError"),

  //NEW
  language: translate("language"),
  tipPopupText: translate('tipPopupText'),
  chooseLanguage: translate('chooseLanguage'),
  scheduleSummary: translate('scheduleSummary'),
  packageDetails: translate('packageDetails'),
  dateAndTime: translate('dateAndTime'),
  description: translate('description'),
  amount : translate('amount')

  // customer: "Customer",
  // worker: "Worker",
  // pleaseSignInToContinue: "Please sign in to continue",
  // signIn: "Sign In",
  // forgot: "Forgot?",
  // name: "Name",
  // phone: "Phone",
  // or: "OR",
  // loginWithSocialMedia: "Login with social media",
  // dontHaveAnAccount: "Dont have an account?",
  // username: "Username",
  // email: "Email",
  // password: "Password",
  // phoneNumber: "Phone Number",
  // confirmPassword: "Confirm Password",
  // signUp: "Sign Up",
  // alreadyHaveAnAccount: "Already have an account?",
  // myJobs: "My Jobs",
  // requests: "Requests",
  // todo: "Todo",
  // onGoing: "Ongoing",
  // done: "Done",
  // componayProfile: "Company Profile",
  // notifications: "Notifications",
  // settings: "Settings",
  // logout: "Logout",
  // accept: "Accept",
  // reject: "Reject",
  // startService: "Start Service",
  // details: "Details",
  // book: "Book",
  // nearBy: "Near By",
  // specialOffers: "Special Offers",
  // allServiceProvides: "All Service Provides",
  // about: "ABOUT",
  // services: "SERVICES",
  // address: "Address",
  // workingHours: "Working Hours",
  // packages: "Packages",
  // package: "Package",
  // schedule: "Schedule",
  // chooseDate: "Choose Date",
  // chooseTime: "Choose Time",
  // discountCode: "Discount Code",
  // scheduleNow: "Schedule Now",
  // home: "Home",
  // myBookings: "My Bookings",
  // rateApplication: "Rate Application",
  // inviteFriends: "Invite Friends",
  // profile: "Profile",
  // serviceDetails: "Service Details",
  // editProfile: "Edit Profile",
  // alert: "Alert",
  // ok: "OK",
  // alertEmail: "Enter valid email address",
  // alertPassword: "Enter password",
  // alertUsername: "Enter username",
  // alertConfirmPassword: "Confirm your password",
  // alertPasswordNotMatch: "Password does not match",
  // alertCurrentPassword: "Enter current password",
  // alertPhoneNo: "Enter phone number",
  // alertNewPassword: "Enter new password",
  // submit: "Submit",
  // changePassword: "Change Password",
  // aboutUs: "About Us",
  // privacyPolicy: "Privacy Policy",
  // termsAndCondition: "Terms and Conditions",
  // currentPassword: "Current Password",
  // newPassword: "New Password",
  // alertNewPasswordNotMatch: "New & confirm password does not match",
  // scheduled: "Scheduled",
  // completed: "Completed",
  // confirm: "Confirm",
  // id: "ID",
  // save: "Save",
  // alertChooseDate: "Choose a date",
  // alertChooseTime: "Choose a time",
  // alertWrongDate: "You cannot request a schedule date that has already passed",
  // alertWrongTime: "You cannot request a schedule time for today that has already passed",
  // search: "Search",
  // map: "Map",
  // currentLocation: "Current Location",
  // useCurrentLocation: "Use Current Location",
  // changeLocation: "Change Location",
  // enterLocation : "Enter Location",
  // go : "GO",
  // alertLocationPermissionDenied : "Location permission denied",
  // alertLocationPositionUnavailable : "No loclation provider available",
  // alertLocationRequestTimeout : "Location request timeout",
  // alertSuccessSchedule : "Your request has been submitted",
  // noServicesFound : "No Services Found",
  // status : "Status",
  // alertUnknownError : "Unknown error. Please try again later"
}